[mgr]
ratio = [1, 2, 5]
# This prevents the cursor from jumping from the bottom to the top
scrolloff = 5

[preview]
# adapter = "wezterm"
adapter = "kitty"
max_width = 2500
max_height = 2500
image_filter = "lanczos3"
wrap = "no"

[opener]
image = [
    { run = 'open "$@"', desc = "Open image" }
]

[open]
rules = [
    { mime = "image/*", use = "image" },
]
